_target_: bayesflow.networks.CouplingFlow
depth: 6
subnet: mlp
transform: affine
permutation: random
use_actnorm: true
base_distribution: normal
coupling_kwargs:
  subnet_kwargs:
    widths:
      _target_: sweeper.constant_list
      length: ${inference_mlp_depth}
      value:
        _target_: builtins.pow
        base: 2
        exp: ${inference_mlp_width}
    kernel_initializer: he_normal
    activation: mish
    dropout: 0
    residual: false
    spectral_normalization: false
