_target_: bayesflow.networks.FlowMatching
subnet: mlp
subnet_kwargs:
  _target_: builtins.dict
  widths:
    _target_: sweeper.constant_list
    length: ${inference_mlp_depth}
    value:
      _target_: builtins.pow
      base: 2
      exp: ${inference_mlp_width}
  dropout: 0.00
  activation: mish
  kernel_initializer: he_normal
  residual: false
  spectral_normalization: false
base_distribution: normal
loss_fn: mse
use_optimal_transport: false
optimal_transport_kwargs: null
integrate_kwargs:
  _target_: builtins.dict
  method: euler
  steps: 100
