_target_: bayesflow.networks.FlowMatching
subnet: mlp
subnet_kwargs:
  _target_: builtins.dict
  widths: [512, 512, 512]
  dropout: 0.05
base_distribution: normal
integrator: euler
use_optimal_transport: false
optimal_transport_kwargs: null
