# defaults:
# - base_summary_network

_target_: bayesflow.networks.DeepSet
summary_dim: 16
depth: 2
inner_pooling: mean
output_pooling: mean
mlp_widths_equivariant: [64, 64]
mlp_widths_invariant_inner: [64, 64]
mlp_widths_invariant_outer: [64, 64]
mlp_widths_invariant_last: [64, 64]
activation: gelu
kernel_initializer: he_normal
dropout: 0.00
spectral_normalization: false
