defaults:
- base_summary_network

_target_: bayesflow.networks.SetTransformer
summary_dim: ${summary_dim}
embed_dims: 
  _target_: sweeper.constant_list
  length: ${summary_embed_depth}
  value:
    _target_: builtins.pow
    base: 2
    exp: ${summary_embed_width}
num_heads: 
  _target_: sweeper.constant_list
  length: ${summary_embed_depth}
  value: 4
num_seeds: ${summary_num_seeds}
dropout: 0.00
expansion_factor: ${summary_expansion_factor}
