defaults:
- base_summary_network

_target_: bayesflow.networks.SetTransformer
summary_dim: 16
embed_dims: 
  _target_: sweeper.constant_list
  length: ${embed_depth}
  value:
    _target_: builtins.pow
    base: 2
    exp: ${embed_width}
num_heads: 
  _target_: sweeper.constant_list
  length: ${embed_depth}
  value: 4
num_seeds: 4
dropout: 0.00
expansion_factor: 4.0
