_target_: bayesflow.simulators.LambdaSimulator
sample_fn:
  _target_: priors.rdm_prior_simple
  _partial_: true
  drift_intercept_loc: 1
  drift_intercept_scale: 0.5
  drift_slope_loc: 1.5
  drift_slope_scale: 0.5
  sd_true_shape: 12
  sd_true_scale: 0.1
  threshold_shape: 8
  threshold_scale: 0.15
  t0_loc: 0.3
  t0_scale: 0.2
  t0_lower: 0.0
  rng:
    _target_: numpy.random.default_rng
    seed: ${seed}