"""Validate the RDM and LBA likelihoods against EMC2, the reference implementation.

`tests/test_rdm_jax.py` and `tests/test_lba_jax.py` check these densities against *internal*
references -- `scipy.stats.invgauss` for the RDM's Wald primitives, and `scipy.integrate.quad`
self-consistency for the LBA (scipy has no LBA closed form). Neither pins the assembled race
likelihood to an independent implementation of the same models. EMC2 (Stevenson, Donzallaz,
Heathcote et al.) is that implementation, and this module compares against it.

The comparison runs off CSV fixtures in `tests/reference/`, generated by the committed
`tests/reference/generate_emc2_reference.R` -- so the suite needs no R, and a future EMC2
change shows up as a regeneration diff rather than a silent pass. That script's header
documents the parameter mapping between the two packages; the short version is that EMC2's RDM
takes `v, B, A, t0, s` with our threshold as `B` and `A = 0` (we have no start-point
variability), while its LBA takes the decision time `rt - t0`, the threshold `b = A + B`, and
our per-accumulator `s` as `sv`.

Two places where the two implementations legitimately differ, both measured rather than
assumed, and both bounded by the tolerances below:

1. EMC2's `pWald` carries about six digits, where `rdm_jax.inv_gauss_logsf` reproduces
   `scipy.stats.invgauss.logsf` exactly (that is what `test_inv_gauss_logsf` already pins). So
   the RDM survival tolerance here is deliberately loose, and it is EMC2 that is the looser
   side -- not a defect on our end.
2. The LBA density is a difference of nearly equal terms and underflows in float64 at small
   decision times, where EMC2's C++ kernel keeps going. `lba_logpdf` floors at `min_p` there,
   which is the same constant EMC2's own `log_likelihood_race` floors each trial at, so the two
   agree once that floor is applied. The floor engages slightly early when the start-point
   range `A` is well below 1 (the floored quantity is the density times `A`), which
   `FLOOR_BAND_NATS` bounds.
"""

import re
from pathlib import Path
import jax.numpy as jnp
import numpy as np
import pandas as pd
import pytest
from lba_jax import _lba_simple_log_likelihood
from lba_jax import lba_logpdf
from lba_jax import lba_logsf
from lba_jax import lba_race_logpdf
from rdm_jax import _rdm_simple_log_likelihood
from rdm_jax import inv_gauss_logpdf
from rdm_jax import inv_gauss_logsf
from rdm_jax import rdm_race_logpdf

REFERENCE_DIR = Path(__file__).parent / "reference"

# EMC2's log_likelihood_race floors every trial at min_ll = log(1e-10); rdm_jax/lba_jax use the
# same 1e-10 as min_p. Comparing floored values is therefore apples-to-apples, and is what
# actually enters either package's likelihood.
MIN_LL = float(np.log(1e-10))

# How far above the floor EMC2's LBA density is still allowed to be on rows where ours has
# floored. The gap is `-log(A)`-ish, so it only opens up for A far below the prior's range
# (Gamma(6, 0.1), mean 0.6); the fixture's A = 0.05 edge rows are the ones that reach it.
FLOOR_BAND_NATS = 3.5

# The LBA density is a difference of nearly equal terms, so its relative precision decays
# smoothly as the density falls towards the floor -- measured across the fixture, agreement
# with EMC2 goes 3e-10 (10+ nats of headroom) -> 6e-9 (5 nats) -> 5e-8 (at the floor). Rows
# with less headroom than this are held to the looser `NEAR_FLOOR_TOL` instead.
HEADROOM_NATS = 5.0
NEAR_FLOOR_TOL = 1e-6


def _read_fixture(name):
    return pd.read_csv(REFERENCE_DIR / name, comment="#")


def _read_header_params(name):
    """Pull the `# key=value` provenance lines off a dataset fixture."""
    params = {}
    with (REFERENCE_DIR / name).open() as handle:
        for line in handle:
            if not line.startswith("#"):
                break
            params.update({k: float(v) for k, v in re.findall(r"(\w+)=([-\d.eE+]+)", line)})
    return params


def _relerr(ref, res):
    # Same idiom as test_inv_gauss_logsf: absolute error once |ref| drops below 1, so that
    # log-densities near zero do not manufacture a huge relative error.
    return np.abs(np.asarray(ref) - np.asarray(res)) / np.maximum(np.abs(np.asarray(ref)), 1.0)


# ---------------------------------------------------------------------------
# RDM
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def rdm_points():
    return _read_fixture("emc2_rdm_pointwise.csv")


def test_rdm_logpdf_matches_emc2(rdm_points):
    d = rdm_points
    ours = np.array(
        inv_gauss_logpdf(
            jnp.array((d.rt - d.t0).to_numpy()),
            (d.b / d.v_win).to_numpy(),
            ((d.b / d.s_win) ** 2).to_numpy(),
        ),
    )
    # EMC2 returns a density of exactly 0 (log -inf) once its own Wald underflows; those rows
    # carry no information about agreement, and the floored race test below covers them.
    finite = np.isfinite(d.log_pdf.to_numpy())
    assert finite.sum() > 250
    assert _relerr(d.log_pdf.to_numpy()[finite], ours[finite]).max() < 1e-9


def test_rdm_logsf_matches_emc2(rdm_points):
    d = rdm_points
    ours = np.array(
        inv_gauss_logsf(
            jnp.array((d.rt - d.t0).to_numpy()),
            (d.b / d.v_lose).to_numpy(),
            ((d.b / d.s_lose) ** 2).to_numpy(),
        ),
    )
    ref = d.log_sf.to_numpy()
    finite = np.isfinite(ref)
    sf = np.exp(ref)

    # Two tiers, because EMC2 evaluates the survival function as `1 - pWald(...)` in linear
    # space: the deeper the tail, the more of it is cancellation error. Ours matches scipy to
    # full double precision throughout (test_inv_gauss_logsf), so these bounds describe EMC2's
    # accuracy, not ours.
    bulk = finite & (sf >= 1e-4)
    tail = finite & (sf < 1e-4)
    assert _relerr(ref[bulk], ours[bulk]).max() < 1e-5
    assert _relerr(ref[tail], ours[tail]).max() < 1e-3


def test_rdm_race_logpdf_matches_emc2(rdm_points):
    d = rdm_points
    ours = np.array(
        rdm_race_logpdf(
            jnp.array(d.rt.to_numpy()),
            d.v_win.to_numpy(),
            d.v_lose.to_numpy(),
            d.s_win.to_numpy(),
            d.s_lose.to_numpy(),
            d.b.to_numpy(),
            d.t0.to_numpy(),
        ),
    )
    ref = np.maximum(d.log_race.to_numpy(), MIN_LL)
    assert _relerr(ref, np.maximum(ours, MIN_LL)).max() < 1e-5


def test_rdm_total_log_likelihood_matches_emc2():
    # Per-accumulator agreement cannot catch a swapped winner/loser role or a mis-assigned
    # s_true / s_false, because those are decided in _rdm_simple_log_likelihood rather than in
    # the density functions. Scoring a whole dataset from (rt, choice) alone does.
    truth = _read_header_params("emc2_rdm_dataset.csv")
    d = _read_fixture("emc2_rdm_dataset.csv")

    ours = float(
        _rdm_simple_log_likelihood(
            jnp.array(d.rt.to_numpy()),
            jnp.array(d.choice.to_numpy() == 1),
            truth["v_intercept"],
            truth["v_slope"],
            truth["s_true"],
            truth["b"],
            truth["t0"],
        ),
    )
    assert _relerr(truth["total_log_likelihood"], ours) < 1e-9


# ---------------------------------------------------------------------------
# LBA
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def lba_points():
    return _read_fixture("emc2_lba_pointwise.csv")


def test_lba_logpdf_matches_emc2_where_representable(lba_points):
    d = lba_points
    ours = np.array(
        lba_logpdf(
            jnp.array((d.rt - d.t0).to_numpy()),
            d.v_win.to_numpy(),
            d.sv_win.to_numpy(),
            d.A.to_numpy(),
            (d.A + d.B).to_numpy(),
        ),
    )
    ref = d.log_pdf.to_numpy()
    above_floor = ~np.isclose(ours, MIN_LL)
    well_conditioned = above_floor & (ours - MIN_LL > HEADROOM_NATS)
    near_floor = above_floor & ~well_conditioned

    assert well_conditioned.sum() > 300
    assert _relerr(ref[well_conditioned], ours[well_conditioned]).max() < 1e-8
    assert _relerr(ref[near_floor], ours[near_floor]).max() < NEAR_FLOOR_TOL


def test_lba_logpdf_floor_is_bounded_against_emc2(lba_points):
    # The complement of the test above: wherever our density has floored, EMC2's value must be
    # at or near the floor too. This is the regression test for the floor being applied to the
    # *density* -- flooring the pre-normalization bracket instead (as this once did) returned
    # `-log(A) - log Phi(v/s)` nats *above* the floor, i.e. a tail that was overstated rather
    # than clamped, and at A = 0.6, b = 1.8, v = 3.5, s = 1.2, dt = 0.05 that was -22.51
    # against a true value of e^-146.
    d = lba_points
    ours = np.array(
        lba_logpdf(
            jnp.array((d.rt - d.t0).to_numpy()),
            d.v_win.to_numpy(),
            d.sv_win.to_numpy(),
            d.A.to_numpy(),
            (d.A + d.B).to_numpy(),
        ),
    )
    floored = np.isclose(ours, MIN_LL)
    assert floored.any()
    assert np.all(ours[floored] == pytest.approx(MIN_LL))
    assert (d.log_pdf.to_numpy()[floored] - MIN_LL).max() < FLOOR_BAND_NATS


def test_lba_logsf_matches_emc2(lba_points):
    d = lba_points
    ours = np.array(
        lba_logsf(
            jnp.array((d.rt - d.t0).to_numpy()),
            d.v_lose.to_numpy(),
            d.sv_lose.to_numpy(),
            d.A.to_numpy(),
            (d.A + d.B).to_numpy(),
        ),
    )
    # No tiering needed here: unlike the Wald survival, the LBA's truncated-normal drift leaves
    # a heavy tail, so EMC2's `1 - plba(...)` stays well conditioned across the whole fixture.
    assert _relerr(d.log_sf.to_numpy(), ours).max() < 1e-8


def test_lba_race_logpdf_matches_emc2(lba_points):
    d = lba_points
    ours = np.array(
        lba_race_logpdf(
            jnp.array(d.rt.to_numpy()),
            d.v_win.to_numpy(),
            d.v_lose.to_numpy(),
            d.sv_win.to_numpy(),
            d.sv_lose.to_numpy(),
            d.A.to_numpy(),
            d.B.to_numpy(),
            d.t0.to_numpy(),
        ),
    )
    ref = np.maximum(d.log_race.to_numpy(), MIN_LL)
    floored = np.isclose(ours, MIN_LL)
    well_conditioned = ~floored & (ours - MIN_LL > HEADROOM_NATS)
    near_floor = ~floored & ~well_conditioned

    assert _relerr(ref[well_conditioned], ours[well_conditioned]).max() < 1e-8
    assert _relerr(ref[near_floor], ours[near_floor]).max() < NEAR_FLOOR_TOL
    # Same band as the pointwise density: where we floor, EMC2 must be near the floor as well.
    assert (ref[floored] - MIN_LL).max() < FLOOR_BAND_NATS


def test_lba_total_log_likelihood_matches_emc2():
    truth = _read_header_params("emc2_lba_dataset.csv")
    d = _read_fixture("emc2_lba_dataset.csv")

    ours = float(
        _lba_simple_log_likelihood(
            jnp.array(d.rt.to_numpy()),
            jnp.array(d.choice.to_numpy() == 1),
            truth["v_intercept"],
            truth["v_slope"],
            truth["s_true"],
            truth["A"],
            truth["B"],
            truth["t0"],
        ),
    )
    assert _relerr(truth["total_log_likelihood"], ours) < 1e-9
