_target_: bayesflow.simulators.LambdaSimulator
sample_fn:
  _target_: rdm_jax.rdm_experiment_simple_jax_stateful
  _partial_: true
  s_false: 1
  rng:
    _target_: rdm_jax.SplittableKey
    seed: ${seed}
