_target_: bayesflow.simulators.LambdaSimulator
sample_fn:
  _target_: simulation.rdm_experiment_simple
  _partial_: true
  s_false: 1
  rng:
    _target_: numpy.random.default_rng
    seed: ${seed}
    