_target_: priors.rdmc_prior_simple
_partial_: true
drift_c_intercept_loc: 1
drift_c_intercept_scale: 0.5
drift_c_slope_loc: 1.5
drift_c_slope_scale: 0.5
amp_shape: 5
amp_scale: 0.08
tau_shape: 2
tau_scale: 0.04
sd_true_shape: 12
sd_true_scale: 0.1
threshold_shape: 8
threshold_scale: 0.15
t0_loc: 300
t0_scale: 200
rng:
  _target_: numpy.random.default_rng
  seed: ${seed}