_target_: simulation.batch_simulator
_partial_: true
simulator_fun:
  _target_: priors.rdmc_prior_simple
  _partial_: true
  drift_c_intercept_loc: 0.15
  drift_c_intercept_scale: 0.025
  drift_c_slope_loc: 0.1
  drift_c_slope_scale: 0.025
  amp_shape: 100
  amp_scale: 0.1
  tau_shape: 200
  tau_scale: 0.1
  sd_true_shape: 12
  sd_true_scale: 0.1
  threshold_shape: 100
  threshold_scale: 0.2
  t0_loc: 300
  t0_scale: 200
  rng:
    _target_: numpy.random.default_rng
    seed: ${seed}