_target_: priors.rrdmc_prior_simple
_partial_: true
drift_c_intercept_loc: 0.2
drift_c_intercept_scale: 0.05
drift_c_slope_loc: 0.3
drift_c_slope_scale: 0.05
drift_a_intercept_loc: 0.2
drift_a_intercept_scale: 0.05
drift_a_slope_loc: 0.3
drift_a_slope_scale: 0.05
initial_shape: 5
initial_scale: 1.2
decay_shape: 400
decay_scale: 0.1
sd_true_shape: 12
sd_true_scale: 0.1
threshold_shape: 100
threshold_scale: 0.18
t0_loc: 300
t0_scale: 200
rng:
  _target_: numpy.random.default_rng
  seed: ${seed}