prior_means:
  v_intercept:
    _target_: priors.log_truncated_normal_moments
    loc: ${simulator.prior_fun.drift_intercept_loc}
    scale: ${simulator.prior_fun.drift_intercept_scale}
    moment: m
  v_slope:
    _target_: priors.log_truncated_normal_moments
    loc: ${simulator.prior_fun.drift_slope_loc}
    scale: ${simulator.prior_fun.drift_slope_scale}
    moment: m
  s_true:
    _target_: priors.log_gamma_moments
    shape: ${simulator.prior_fun.sd_true_shape}
    scale: ${simulator.prior_fun.sd_true_scale}
    moment: m
  b:
    _target_: priors.log_gamma_moments
    shape: ${simulator.prior_fun.threshold_shape}
    scale: ${simulator.prior_fun.threshold_scale}
    moment: m
  t0:
    _target_: priors.log_truncated_normal_moments
    loc: ${simulator.prior_fun.t0_loc}
    scale: ${simulator.prior_fun.t0_scale}
    moment: m
prior_stds:
  v_intercept:
    _target_: priors.log_truncated_normal_moments
    loc: ${simulator.prior_fun.drift_intercept_loc}
    scale: ${simulator.prior_fun.drift_intercept_scale}
    moment: v
  v_slope:
    _target_: priors.log_truncated_normal_moments
    loc: ${simulator.prior_fun.drift_slope_loc}
    scale: ${simulator.prior_fun.drift_slope_scale}
    moment: v
  s_true:
    _target_: priors.log_gamma_moments
    shape: ${simulator.prior_fun.sd_true_shape}
    scale: ${simulator.prior_fun.sd_true_scale}
    moment: v
  b:
    _target_: priors.log_gamma_moments
    shape: ${simulator.prior_fun.threshold_shape}
    scale: ${simulator.prior_fun.threshold_scale}
    moment: v
  t0:
    _target_: priors.log_truncated_normal_moments
    loc: ${simulator.prior_fun.t0_loc}
    scale: ${simulator.prior_fun.t0_scale}
    moment: v
