_target_: bayesflow.simulators.LambdaSimulator
sample_fn:
  _target_: design.random_num_obs_discrete
  _partial_: true
  values:
  - 250
  - 500
  - 750
  - 1000
  rng:
    _target_: numpy.random.default_rng
    seed: ${seed}
is_batched: true
