_target_: bayesflow.simulation.Prior
prior_fun:
  _target_: priors.rdm_prior_simple
  _partial_: true
  drift_intercept_loc: 1
  drift_intercept_scale: 0.5
  drift_slope_loc: 1.5
  drift_slope_scale: 0.5
  sd_true_shape: 12
  sd_true_scale: 0.1
  threshold_shape: 8
  threshold_scale: 0.15
  t0_loc: 0.3
  t0_scale: 0.2
  t0_lower: 0.0
  rng:
    _target_: utils.get_default_rng
param_names:
  - $v_{intercept}$
  - $v_{slope}$
  - $s_{true}$
  - b
  - $t_{0}$