# @package _global_

defaults:
  - _self_
  - sweeper: basic
  - experiment: experiment_1
  - approximator: continuous_approximator
  - optimizer: adam_cosine_decay
  - simulator: rdm
  - callbacks: tensorboard
  - model: rdm_simple # Overrides simulator and approximator
  - inference-method: flow_matching # Overrides approximator
  - summary-method: set_transformer
  - mcmc_model_fun: rdm