# @package _global_

hydra:
  job:
    chdir: True
    config:
        override_dirname:
          exclude_keys:
            - i
            - t
  run:
    dir: outputs/${hydra.job.override_dirname}
  job_logging:
    handlers:
      file:
        mode: w

defaults:
  - _self_
  - prior_stats: rdm
  - trainer: settransformer

tags: ["test_npe"]

seed: 2024

test_batch_size: 1000
test_transform: true

test_num_obs:
  _target_: numpy.array
  object: ${trainer.generative_model.simulator.context_generator.non_batchable_context_fun.values}
