# @package _global_

hydra:
  job:
    chdir: True
    env_set:
      KERAS_BACKEND: jax
  run:
    dir: outputs/${hydra.job.override_dirname}
  job_logging:
    handlers:
      file:
        mode: w

defaults:
  - _self_
  - approximator: continuous_approximator
  - simulator: rdm
  - optimizer: adam
  - callbacks: tensorboard
  - prior_stats: rdm

tags: ["train_npe"]

seed: 2024

diag_batch_size: 100
diag_sbc_num_posterior_samples: 100
diag_sens_num_posterior_samples: 100

diag_num_obs:
  _target_: numpy.array
  object: ${simulator.design_fun.values}

epochs: 100
iterations_per_epoch: 500
batch_size: 64
