# @package _global_

defaults:
- override /simulator: rdm_meta
- override /mcmc_model_fun: rdm_meta

is_meta: true

mcmc_sampling_fun:
  init_position:
    _target_: numpy.array
    object:
      - 1.5
      - 0.15
      - 1
      - 2
      - 1
      - 1
      - 0.2
