# @package _global_

defaults:
- override /simulator: rdm
- override /approximator/adapter: rdm_simple

simulator.design_simulator.sample_fn.values:
  _target_: numpy.arange
  start: 50
  stop: 250
  step: 50
