_target_: keras.optimizers.Adam
learning_rate:
  _target_: keras.optimizers.schedules.CosineDecay
  initial_learning_rate: 5e-4
  decay_steps:
    _target_: utils.get_decay_steps
    num_epochs: ${epochs}
    num_batches: ${iterations_per_epoch}
  alpha: 1e-6
clipnorm: 1.0
