_target_: simulation.create_data_adapter
inference_variables: ["v_c_intercept", "v_c_slope", "amp", "tau", "s_true", "b", "t0"]
inference_conditions:
- num_obs
summary_variables:
- x
transforms:
- _target_: bayesflow.adapters.transforms.FilterTransform # Log transform params
  transform_constructor: 
    _target_: bayesflow.adapters.transforms.LambdaTransform
    _partial_: true
    forward:
      _target_: simulation.log_transform
    inverse:
      _target_: simulation.inverse_log_transform
  exclude: ["num_obs", "x"]
- _target_: bayesflow.adapters.transforms.FilterTransform # Sqrt transform num_obs
  transform_constructor: 
    _target_: bayesflow.adapters.transforms.LambdaTransform
    _partial_: true
    forward:
      _target_: simulation.sqrt_transform
    inverse:
      _target_: simulation.inverse_sqrt_transform
  include: ["num_obs"]
- _target_: bayesflow.adapters.transforms.FilterTransform # Standardize params and x
  transform_constructor: 
    _target_: bayesflow.adapters.transforms.Standardize
    _partial_: true
  exclude: ["num_obs"]
