defaults:
  - generative_model: rdm

_target_: bayesflow.trainers.Trainer
amortizer:
  _target_: bayesflow.amortizers.AmortizedPosterior
  inference_net:
    _target_: bayesflow.inference_networks.InvertibleNetwork
    num_params: 5
    num_coupling_layers: 6
    coupling_design: affine
  summary_net:
configurator:
  _target_: configuration.rdm_configurator_simple
  _partial_: true
  prior_means: ${prior_stats.prior_means}
  prior_stds: ${prior_stats.prior_stds}
  transform_fun:
    _target_: numpy.log
    _partial_: true
default_lr: 0.00005
checkpoint_path: checkpoints
skip_checks: false