defaults:
  - _trainer

amortizer:
  summary_net:
    _target_: bayesflow.summary_networks.SetTransformer
    input_dim: 2
    attention_settings:
      num_heads: 4
      key_dim: 32
      dropout: 0.1
    dense_settings: null
    use_layer_norm: false
    num_dense_fc: 2
    summary_dim: 32
    num_attention_blocks: 2
    num_inducing_points: 32
    num_seeds: 1