defaults:
  - prior: simple

_target_: bayesflow.simulation.GenerativeModel
simulator:
  _target_: bayesflow.simulation.Simulator
  simulator_fun:
    _target_: simulation.rdm_experiment_simple
    _partial_: true
    rng:
      _target_: numpy.random.default_rng
      seed: ${seed}
  context_generator:
    _target_: bayesflow.simulation.ContextGenerator
    non_batchable_context_fun:
      _target_: design.random_num_obs_discrete
      _partial_: true
      values:
      - 100
      - 250
      - 500
      - 1000
      rng:
        _target_: numpy.random.default_rng
        seed: ${seed}
skip_test: false